### ISSUE TITLE
possible eval bug with exit

### ISSUE THREAD

**Issue by isaacl** [georgvonzimmermann/Sunsetter8#12]
I noticed a swing in score after using exit.

```
xboard
reset crazyhouse
setboard r1b2rk1/ppp2ppp/1b1p4/4p1Q1/2B1P3/2PP3P/PP2nPPK/RN3R2/QNbn b - - 25 13
analyze
7 119 0 2566 B@f4 g5f4 e2f4 N@f5
...
17 38 857 10572577 B@f4 g5f4 e2f4 Q@g3 N@e2
```

Same after moving

```
B@f4
7 134 0 4291 g5f4 e2f4
...
16 55 399 5112656 g5f4 e2f4 Q@g3 N@e2 g3g5 f4e6 N@e7 g8h8 g5f5
```

But when I reset back to the first position, sunsetter now evals differently!

```
exit
setboard r1b2rk1/ppp2ppp/1b1p4/4p1Q1/2B1P3/2PP3P/PP2nPPK/RN3R2/QNbn b - - 25 13
analyze
7 -271 0 2566 B@f4 g5f4 e2f4 N@f5
...
12 -348 19 233588 B@f4 g5f4 e2f4 N@e7 g8h8 Q@g3
```

**Comment by georgvonzimmermann** [comment]
Thanks for the report and the examples. This was a very odd bug in the setboard function. Setboard was using setPieceInHand() function to first set all pieces in Hand to 0. That way the material value for the position was off.
