### ISSUE TITLE
test compiling with gcc

### ISSUE THREAD

**Issue by georgvonzimmermann** [georgvonzimmermann/Sunsetter8#2]
Probably there are some adjustments needed to make it compile smoothly with gcc **(see the readme.TXT)**
Please let me know what needs to be changed, preferably within #ifdef, so that the behaviour compiling with MSVC on windows is not changed.

**Comment by ddugovic** [comment]
I'm not a Linux expert, but maybe on Unix/Linux platforms (non-win32) don't define socklen_t.
