### ISSUE TITLE
xboard sunsetter mate scores off by one

### ISSUE THREAD

**Issue by isaacl** [georgvonzimmermann/Sunsetter8#9]
When analyzing the player which is mated, sunsetter reports the wrong mate score.

```
xboard
reset crazyhouse
tellics kibitz Hello from Sunsetter 9
setboard r3kb1r/ppp2bp1/8/3b3p/3Pb2K/5r1P/P1PQ1PnP/5R2/PQNNPNPPp w kq - 60 31
analyze
```

sunsetter reports:

```
7 -29998 0 507 h4g5 f3f5
```

but it's mate in 1.

**Comment by georgvonzimmermann** [comment]
What Sunsetter is trying to tell us is that there is a mate in 2 ply (= 2 half-moves). I am now trying to change it to xboard-standard.

**Comment by isaacl** [comment]
I think 3 ply and 2 ply mates both had a 29998 score.

If you'd like to use a ply mate formula, that's fine too. Lichess can easily get full moves to mate from ply.

**Comment by isaacl** [comment]
Online docs say crafty has m1 at 32766 and then -1 for each ply. 

With this, I see 32764 for m1, and it only drops every other ply. Can you make it -1 for each ply?
